version: '3'

services:
  node:
    build: .
    command: ['./node_modules/.bin/serve', '--debug']
    labels:
      traefik.frontend.rule: "Host:artcomptantpourrien.localhost"
      traefik.port: "5000"
    user: node
    volumes:
      - ./src:/usr/local/src

  traefik:
    command:
      - --api
      - --docker
      - --defaultentrypoints=https
      - --entryPoints=Name:https Address::443 TLS
    depends_on:
      - node
    image: traefik:1.7-alpine
    labels:
      traefik.frontend.rule: "Host:traefik.artcomptantpourrien.localhost"
      traefik.port: "8080"
    ports:
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
